# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
