# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('State', models.CharField(choices=[(1, 'Alabama'), (2, 'Alaska'), (3, 'Arizona'), (4, 'Arkansas'), (5, 'California'), (6, 'Colorado'), (7, 'Connecticut'), (8, 'Delaware'), (9, 'Florida'), (10, 'Georgia'), (11, 'Hawaii'), (12, 'Idaho'), (13, 'Illinois'), (14, 'Indiana'), (15, 'Iowa'), (16, 'Kansas'), (17, 'Kentucky'), (18, 'Louisiana'), (19, 'Maine'), (20, 'Maryland'), (21, 'Massachusetts'), (22, 'Michigan'), (23, 'Minnesota'), (24, 'Mississippi'), (25, 'Missouri'), (26, 'Montana'), (27, 'Nebraska'), (28, 'Nevada'), (29, 'New Hampshire'), (30, 'New Jersey'), (31, 'New Mexico'), (32, 'New York'), (33, 'North Carolina'), (34, 'North Dakota'), (35, 'Ohio'), (36, 'Oklahoma'), (37, 'Oregon'), (38, 'Pennsylvania'), (39, 'Rhode Island'), (40, 'South Carolina'), (41, 'South Dakota'), (42, 'Tennessee'), (43, 'Texas'), (44, 'Utah'), (45, 'Vermont'), (46, 'Virginia'), (47, 'Washington'), (48, 'West Virginia'), (49, 'Wisconsin'), (50, 'Wyoming')], max_length=20)),
                ('Country', models.CharField(choices=[(1, 'Make a choice'), (2, 'United States')], max_length=50)),
            ],
        ),
    ]
